### ISSUE TITLE
incompleteness section

### ISSUE THREAD

**Issue by HWRix** [wilmatrick/DynamicsPaper1#3]
The current name of the Section says 
![screen shot 2015-02-12 at 15 05 12](https://cloud.githubusercontent.com/assets/5234830/6178906/86e6fa54-b2c8-11e4-9e36-4e97a6b19c22.png)

I think this section is about "incorrect assumptions about the (in-)completeness ; incompleteness is OK, as long as it is well-modelled.

**Comment by wilmatrick** [comment]
Thanks for the hint. I changed the title of the section to "What if our assumptions on the (in-)completeness of the data set are incorrect?".
